apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-app
  labels:
    app: maven-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-web-app
  template:
    metadata:
      labels:
        app: maven-web-app
    spec:
      containers:
      - name: maven-web-app
        image: dockerhub-username/company-webapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: maven-web-app
  ports:
  - port: 80
    targetPort: 8080
